
services:
  server:
    build:
      context: .  # Cartella con il Dockerfile del server
    image: libreria-server:latest 
    container_name: libreria-server
    ports:
      - "8880:8080" 
    depends_on:
      - database  
    networks:
      - mynetwork  

  database:
    image: postgres:latest 
    container_name: postgres-db
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: myuser 
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  # Monta la directory per inizializzare il DB
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

    #external: true
